### ISSUE TITLE
服务列表信息发生改变Higress服务没有及时更新

### ISSUE THREAD

**Issue by yian2333** [higress-group/higress-standalone#48]
higress版本：1.3.1
nacos版本：2.1.1

<img width="1113" alt="bug2" src="https://github.com/higress-group/higress-standalone/assets/129262408/3359ee18-e704-46d7-848a-c6b5ef3433f3">
nacos服务配置的ip端口信息有修改，Higress服务页面正常更新显示，但是实际请求的ip端口还是之前nacos的旧配置
<img width="1619" alt="bug1" src="https://github.com/higress-group/higress-standalone/assets/129262408/3b012c0c-fa85-420f-adbe-2b40235c5131">
重启Higress服务后才生效。

测试过程中日志里出现大量ip，暂未发现其原因，重启之后日志显示正常。
<img width="1648" alt="bug3" src="https://github.com/higress-group/higress-standalone/assets/129262408/aa1920f5-b332-47e8-8c51-ccae9efa22de">

**Comment by johnlanni** [comment]
@yian2333 大量IP是XFF header里的，原因是出现了循环调用链路，我想确认的是你在修改路由和服务来源之后，有确认还有新请求触发这样的日志吗。是否看到的日志是老的。

**Comment by yian2333** [comment]
> @yian2333 大量IP是XFF header里的，原因是出现了循环调用链路，我想确认的是你在修改路由和服务来源之后，有确认还有新请求触发这样的日志吗。是否看到的日志是老的。

修改完路由之后再请求还有这样的日志，之后重启了Higress就没有这样的日志了

**Comment by johnlanni** [comment]
那很奇怪了，新的路由修改生效了，应该整个RDS重新下发了，不会存在老的路由了。
但现在看下发下去的还有老的路由，是否从Nacos处监听配置可能有缓存。@CH3CHO 看看帮忙排查下

**Comment by CH3CHO** [comment]
> > @yian2333 大量IP是XFF header里的，原因是出现了循环调用链路，我想确认的是你在修改路由和服务来源之后，有确认还有新请求触发这样的日志吗。是否看到的日志是老的。
> 
> 修改完路由之后再请求还有这样的日志，之后重启了Higress就没有这样的日志了

“修改完路由之后再请求还有这样的日志”指的是修改完路由之后执行查看日志的命令，命令的输出里还有这样的请求日志吗？当时是否核对了对应日志的记录时间？

因为命名返回的是Higress从启动之后所有的日志。需要根据时间确定那些有问题的日志是修改路由之后记录的还是之前记录的。

**Comment by yian2333** [comment]
> > > @yian2333 大量IP是XFF header里的，原因是出现了循环调用链路，我想确认的是你在修改路由和服务来源之后，有确认还有新请求触发这样的日志吗。是否看到的日志是老的。
> > 
> > 
> > 修改完路由之后再请求还有这样的日志，之后重启了Higress就没有这样的日志了
> 
> “修改完路由之后再请求还有这样的日志”指的是修改完路由之后执行查看日志的命令，命令的输出里还有这样的请求日志吗？当时是否核对了对应日志的记录时间？
> 
> 因为命名返回的是Higress从启动之后所有的日志。需要根据时间确定那些有问题的日志是修改路由之后记录的还是之前记录的。

可以确定是看到的是最新的日志，修改配置后请求还是有很多ip，因为当时日志太多了，没有截图。

**Comment by CH3CHO** [comment]
那能简单描述一下修改前和修改后的完整路由配置吗，包括以下信息：
- 一共配了几条路由
- 每条路由分别关联了哪些域名（是一个域名还是不同的域名）
- 这些域名使用的什么协议（HTTP/HTTPS）
- 各个路由的匹配条件是什么（精确或前缀，匹配值是什么）
- 路由指向的服务是什么类型的（Nacos还是固定地址）
- 删除的是哪一条或哪几条路由
- 出问题的请求对应的是哪条路由

**Comment by yian2333** [comment]
> 那能简单描述一下修改前和修改后的完整路由配置吗，包括以下信息：
> 
>     * 一共配了几条路由
> 
>     * 每条路由分别关联了哪些域名（是一个域名还是不同的域名）
> 
>     * 这些域名使用的什么协议（HTTP/HTTPS）
> 
>     * 各个路由的匹配条件是什么（精确或前缀，匹配值是什么）
> 
>     * 路由指向的服务是什么类型的（Nacos还是固定地址）
> 
>     * 删除的是哪一条或哪几条路由
> 
>     * 出问题的请求对应的是哪条路由
1.一共只配置了一个路由
2.没有关联域名
3.
4.从精准改成了前缀，匹配值是/api
5.路由指向的服务类型是Nacos
6.没有删除路由，是修改路由配置
7.出问题是就是当前唯一的这一条路由

**Comment by CH3CHO** [comment]
> > 那能简单描述一下修改前和修改后的完整路由配置吗，包括以下信息：
> > ```
> > * 一共配了几条路由
> > 
> > * 每条路由分别关联了哪些域名（是一个域名还是不同的域名）
> > 
> > * 这些域名使用的什么协议（HTTP/HTTPS）
> > 
> > * 各个路由的匹配条件是什么（精确或前缀，匹配值是什么）
> > 
> > * 路由指向的服务是什么类型的（Nacos还是固定地址）
> > 
> > * 删除的是哪一条或哪几条路由
> > 
> > * 出问题的请求对应的是哪条路由
> > ```
> 
> 1.一共只配置了一个路由 2.没有关联域名 3. 4.从精准改成了前缀，匹配值是/api 5.路由指向的服务类型是Nacos 6.没有删除路由，是修改路由配置 7.出问题是就是当前唯一的这一条路由

就是精准匹配那个 /api 的路由是吗？你前面提到过创建过一个指向域名的服务来源，后面又把这个服务来源删掉了。这个服务来源配置过路由吗？

**Comment by johnlanni** [comment]
@yian2333 麻烦回复下，方便我们定位问题，因为目前复现不出这个问题

**Comment by CH3CHO** [comment]
Close due to inactivity.
