### ISSUE TITLE
能否支持 envoyfilter 用于解决部分转发问题

### ISSUE THREAD

**Issue by h31105** [higress-group/higress-standalone#56]
如题，后续版本是否能 支持envoyfilter 用于解决部分使用中的问题：

https://github.com/alibaba/higress/issues/643
https://github.com/alibaba/higress/issues/808

谢谢

**Comment by CH3CHO** [comment]
这个后面会支持的，已经在调研了。

**Comment by CH3CHO** [comment]
已解决：https://github.com/higress-group/higress-standalone/pull/65
