### ISSUE TITLE
采用all-in-one打包为一个镜像，首次运行正常，重启后apiserver无法启动

### ISSUE THREAD

**Issue by huangye123** [higress-group/higress-standalone#70]
采用all-in-one目录的Dockerfile构建镜像，首次启动正常
docker build -t higress .
docker run -d -p 80:80 -p 8080:8080 higress

![image](https://github.com/higress-group/higress-standalone/assets/28778519/df1869f0-1480-4bc6-b914-b73a49e912d0)

服务重启后，apiserver无法正常启动，是否需要配置相关参数

![image](https://github.com/higress-group/higress-standalone/assets/28778519/e8b1d623-7f08-4c70-9eab-a1f276f58298)

**Comment by CH3CHO** [comment]
这个默认用的是文件配置管理方式，是需要mount一个volume到/data目录的。你mount一下试试。

**Comment by huangye123** [comment]
> 这个默认用的是文件配置管理方式，是需要mount一个volume到/data目录的。你mount一下试试。

测试了，还是apiServer启动失败
docker run -d -p 80:80 -p 8080:8080 -v /data/defaultConfig:/opt/data/defaultConfig www.myhuangye.com:8443/basic/higress:1.3.5

**Comment by CH3CHO** [comment]
只需要mount到/data下，不要指定子目录

**Comment by CH3CHO** [comment]
如果还不行的话，麻烦提供一下容器里的 `/var/log/higress/apiserver.log` 日志文件。

**Comment by huangye123** [comment]
> 如果还不行的话，麻烦提供一下容器里的 `/var/log/higress/apiserver.log` 日志文件。

【apiserver.log日志】
Mode=full
rm: cannot remove '/opt/data/defaultConfig/ingresses/higress-console.yaml': No such file or directory
Mode=full
rm: cannot remove '/opt/data/defaultConfig/ingresses/higress-console.yaml': No such file or directory
Mode=full
rm: cannot remove '/opt/data/defaultConfig/ingresses/higress-console.yaml': No such file or directory
Mode=full
rm: cannot remove '/opt/data/defaultConfig/ingresses/higress-console.yaml': No such file or directory

【调整后启动命令】
docker run --name higress -d -p 80:80 -p 8080:8080 -v /opt/data:/opt/data www.myhuangye.com:8443/basic/higress:1.3.5

【问题分析】
1、apiserver在首次启动成功后，会删除/opt/data/defaultConfig/ingresses/higress-console.yaml文件
2、apiserver再次启动时，会因找不到/opt/data/defaultConfig/ingresses/higress-console.yaml而失败
3、将/opt/data/defaultConfig/ingresses/higress-console.yaml设置为只读，重启服务也可以正常启动

**Comment by CH3CHO** [comment]
是个bug，你额外加个参数 `-e ENABLE_CONSOLE_ROUTE=1` 应该就可以了。后面我修一下。

**Comment by CH3CHO** [comment]
不对，有个问题。`/opt/data/defaultConfig/ingresses/higress-console.yaml` 这个文件是打在镜像里的。重新启动镜像怎么会被删掉呢？

**Comment by huangye123** [comment]
> 不对，有个问题。`/opt/data/defaultConfig/ingresses/higress-console.yaml` 这个文件是打在镜像里的。重新启动镜像怎么会被删掉呢？

1、采用docker compose 部署，没有用K8S，对docker容器执行restart后，容器中原本读写层里对临时数据还在。

2、只删除了这个容器，重新创建的容器是基于镜像的只读层然后挂载上新的空的读写层，此时临时数据就不在的，

3、而/opt/data/defaultConfig/ingresses/higress-console.yaml就恢复了。所有在实际测试过程，就是重新创建出来容器，首次是可以正常启动的。

**Comment by CH3CHO** [comment]
> > 不对，有个问题。`/opt/data/defaultConfig/ingresses/higress-console.yaml` 这个文件是打在镜像里的。重新启动镜像怎么会被删掉呢？
> 
> 1、采用docker compose 部署，没有用K8S，对docker容器执行restart后，容器中原本读写层里对临时数据还在。
> 
> 2、只删除了这个容器，重新创建的容器是基于镜像的只读层然后挂载上新的空的读写层，此时临时数据就不在的，
> 
> 3、而/opt/data/defaultConfig/ingresses/higress-console.yaml就恢复了。所有在实际测试过程，就是重新创建出来容器，首次是可以正常启动的。

好的，那了解了。我这里优化一下吧，保证重复删除不会报错。

**Comment by CH3CHO** [comment]
可以参考上面的 PR 本地修复一下。
