### ISSUE TITLE
采用all-in-one打包部署，系统配置数据文件映射路径

### ISSUE THREAD

**Issue by huangye123** [higress-group/higress-standalone#72]
目前Docker命令

docker run --name higress -d -p 80:80 -p 8080:8080 -e ENABLE_CONSOLE_ROUTE=1 -v /data/higress/data:/opt/data -v /data/higress/log:/var/log/higress/ www.myhuangye.com:8443/basic/higress:1.3.5

【问题】
进入登录系统配置成功后，没有删除物理机映射目录情况，重新创建容器时，会了出现需要重新初始化管理员密码，重新配置路由规则

【咨询】
用户在界面配置的信息，存储的路径是哪个呢，需要映射到物理机

**Comment by CH3CHO** [comment]
你映射的不对吧，配置文件是存在/data目录下面的。

参考一下我本地运行的命令：

```powershell
docker run --name higress -it --rm -p 127.0.0.1:28080:8080 -p 127.0.0.1:15014:15014 -p 127.0.0.1:18080:80 -p 127.0.0.1:18443:443 -e MODE=full -e ENABLE_CONSOLE_ROUTE=0 --cpus="0.5" --memory=512m --mount type=bind,source=c:\temp\higress,target=/data higress-aio:0.0.1
```

**Comment by huangye123** [comment]
【已解决】
docker run --name higress -d -p 80:80 -p 8080:8080 -e ENABLE_CONSOLE_ROUTE=1 -v /data/higress/data:/data/ -v /data/higress/config:/opt/data -v /data/higress/log:/var/log/higress/ www.myhuangye.com:8443/basic/higress:1.3.5

/data 是用户配置数据
/opt/data 是应用配置文件

感谢技术支持，data目录有两个，搞混了。
